import { Game, BannerData } from './types';

export const bannerData: BannerData = {
  id: 'banner-1',
  title: 'Hot New Release: Mystic Fortune Deluxe',
  subtitle: 'Experience the ultimate gaming adventure - Available Now!',
  imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&h=400&fit=crop',
  gameId: 'game-1',
  gameProfileUrl: '/marketplace/games/mystic-fortune-deluxe',
};

export const mockGames: Game[] = [
  {
    id: 'game-1',
    name: 'Mystic Fortune Deluxe',
    description: 'An immersive slot game with cascading reels and multiple bonus features. Experience ancient mysticism combined with modern gaming mechanics.',
    imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop',
    releaseDate: '2025-12-01T00:00:00Z',
    availableDate: '2025-12-01T00:00:00Z',
    status: 'released',
    variants: [
      { id: 'var-1-1', name: 'Standard', description: 'Classic gameplay experience' },
      { id: 'var-1-2', name: 'High Roller', description: 'Enhanced bet limits for VIP players' },
      { id: 'var-1-3', name: 'Mobile Optimized', description: 'Optimized for mobile devices' },
    ],
    profileUrl: '/marketplace/games/mystic-fortune-deluxe',
    marketingAssetsUrl: '/marketplace/assets/mystic-fortune-deluxe',
    category: 'Slots',
    features: ['Cascading Reels', 'Free Spins', 'Multipliers', 'Wild Symbols'],
    provider: 'Playtech',
  },
  {
    id: 'game-2',
    name: 'Dragon\'s Gold Megaways',
    description: 'A revolutionary Megaways slot featuring up to 117,649 ways to win. Breathtaking graphics and innovative gameplay mechanics.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=300&fit=crop',
    releaseDate: '2025-12-15T00:00:00Z',
    availableDate: '2025-12-18T00:00:00Z',
    status: 'upcoming',
    variants: [
      { id: 'var-2-1', name: 'Standard', description: 'Classic Megaways experience' },
      { id: 'var-2-2', name: 'Enhanced RTP', description: 'Increased return to player' },
      { id: 'var-2-3', name: 'Bonus Buy', description: 'Feature to purchase bonus rounds' },
      { id: 'var-2-4', name: 'Jackpot', description: 'Progressive jackpot variant' },
    ],
    marketingAssetsUrl: '/marketplace/assets/dragons-gold-megaways',
    category: 'Slots',
    features: ['Megaways', 'Cascading Wins', 'Free Spins', 'Progressive Jackpot'],
    provider: 'Playtech',
  },
  {
    id: 'game-3',
    name: 'Roulette Royal VIP',
    description: 'Premium European Roulette with exclusive VIP features and enhanced betting options for sophisticated players.',
    imageUrl: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?w=400&h=300&fit=crop',
    releaseDate: '2025-12-20T00:00:00Z',
    availableDate: '2025-12-20T00:00:00Z',
    status: 'upcoming',
    variants: [
      { id: 'var-3-1', name: 'Standard VIP', description: 'Enhanced table limits' },
      { id: 'var-3-2', name: 'Ultra VIP', description: 'Unlimited betting for premium players' },
    ],
    marketingAssetsUrl: '/marketplace/assets/roulette-royal-vip',
    category: 'Table Games',
    features: ['Live Dealer', 'HD Streaming', 'VIP Tables', 'Special Bets'],
    provider: 'Playtech',
  },
  {
    id: 'game-4',
    name: 'Blackjack Perfect Pairs',
    description: 'Classic Blackjack with the exciting Perfect Pairs side bet. Optimized for both desktop and mobile play.',
    imageUrl: 'https://images.unsplash.com/photo-1571988775089-85e3c8e74e6d?w=400&h=300&fit=crop',
    releaseDate: '2025-12-28T00:00:00Z',
    availableDate: '2026-01-05T00:00:00Z',
    status: 'upcoming',
    variants: [
      { id: 'var-4-1', name: 'Standard', description: 'Classic blackjack rules' },
      { id: 'var-4-2', name: 'Multi-hand', description: 'Play up to 5 hands simultaneously' },
      { id: 'var-4-3', name: 'VIP', description: 'Higher table limits' },
    ],
    category: 'Table Games',
    features: ['Perfect Pairs', 'Multi-hand', '21+3 Side Bet', 'Insurance'],
    provider: 'Playtech',
  },
  {
    id: 'game-5',
    name: 'Aztec Treasure Quest',
    description: 'Embark on an adventure through ancient Aztec temples. Features expanding wilds and a unique pick-and-win bonus game.',
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=300&fit=crop',
    releaseDate: '2026-01-10T00:00:00Z',
    availableDate: '2026-01-15T00:00:00Z',
    status: 'upcoming',
    variants: [
      { id: 'var-5-1', name: 'Standard', description: 'Original gameplay' },
      { id: 'var-5-2', name: 'Enhanced', description: 'Additional bonus features' },
      { id: 'var-5-3', name: 'Jackpot Edition', description: 'With progressive jackpot' },
    ],
    category: 'Slots',
    features: ['Expanding Wilds', 'Pick Bonus', 'Free Spins', 'Gamble Feature'],
    provider: 'Playtech',
  },
  {
    id: 'game-6',
    name: 'Mega Spin Poker',
    description: 'Play multiple poker hands simultaneously with this fast-paced video poker variant. Multiple game modes available.',
    imageUrl: 'https://images.unsplash.com/photo-1520869309715-5acf2aa3e60d?w=400&h=300&fit=crop',
    releaseDate: '2026-01-18T00:00:00Z',
    availableDate: '2026-01-18T00:00:00Z',
    status: 'upcoming',
    variants: [
      { id: 'var-6-1', name: 'Jacks or Better', description: 'Classic poker variant' },
      { id: 'var-6-2', name: 'Deuces Wild', description: '2s are wild cards' },
      { id: 'var-6-3', name: 'Joker Poker', description: 'Includes joker wild cards' },
      { id: 'var-6-4', name: 'Multi-Game', description: 'All variants in one' },
    ],
    category: 'Video Poker',
    features: ['Multi-hand Play', 'Double Up', 'Auto Hold', 'Strategy Guide'],
    provider: 'Playtech',
  },
  {
    id: 'game-7',
    name: 'Crystal Cascade',
    description: 'A stunning slot featuring cluster pays and cascading symbols. Watch crystals shatter and create winning combinations.',
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=300&fit=crop',
    releaseDate: '2026-02-01T00:00:00Z',
    availableDate: '2026-02-05T00:00:00Z',
    status: 'upcoming',
    variants: [
      { id: 'var-7-1', name: 'Standard', description: 'Original version' },
      { id: 'var-7-2', name: 'Turbo', description: 'Faster gameplay' },
      { id: 'var-7-3', name: 'Max Win', description: 'Enhanced maximum win potential' },
    ],
    category: 'Slots',
    features: ['Cluster Pays', 'Cascading Symbols', 'Multipliers', 'Free Spins'],
    provider: 'Playtech',
  },
  {
    id: 'game-8',
    name: 'Baccarat Prestige',
    description: 'Elegant baccarat with multiple camera angles and side bets. The ultimate premium casino experience.',
    imageUrl: 'https://images.unsplash.com/photo-1596838132731-3301c3fd4317?w=400&h=300&fit=crop',
    releaseDate: '2026-02-14T00:00:00Z',
    availableDate: '2026-02-14T00:00:00Z',
    status: 'upcoming',
    variants: [
      { id: 'var-8-1', name: 'Classic', description: 'Traditional baccarat rules' },
      { id: 'var-8-2', name: 'Speed', description: 'Faster-paced game rounds' },
      { id: 'var-8-3', name: 'VIP', description: 'Exclusive high-limit tables' },
    ],
    category: 'Table Games',
    features: ['Live Dealer', 'Side Bets', 'Roadmap Display', 'Statistics'],
    provider: 'Playtech',
  },
];
